//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DB_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class realtor_companyEntities1 : DbContext
    {
        public realtor_companyEntities1()
            : base("name=realtor_companyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreements> Agreements { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
